drop table card if exists;
create table card (id bigint generated by default as identity, cert varchar(450), publickey varchar(255), privatekey varchar(128), count int(3), primary key (id));
drop table bluetooth if exists;
create table bluetooth (id bigint generated by default as identity, name varchar(20), address varchar(20), cardid bigint , primary key (id));